"""Add username field to User model

Revision ID: 381d60b9299a
Revises: 
Create Date: 2024-07-01 19:49:08.912383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381d60b9299a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
